version: "3.9"

networks:
  development:
    driver: bridge

volumes:
  grafana-data:

services:
  vscode:
    container_name: developer_sharpbox
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    image: ghcr.io/ulfsoft-harbour/dotnet/sdk-vscode:7.0
    ports:
      - "80:80"
      - "5000:5000"
    volumes:
      - ../:/workspace:delegated
      - ${HOME}/.kube/:/root/.kube:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "while sleep 1000; do :; done"
