apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pre-stop
spec:
  containers:
  - image: busybox:1.35.0
    name: main
    args:
    - sleep
    - "10000000"
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "echo 'Execute PreStop' > /var/term"]
  terminationGracePeriodSeconds: 60